package org.iesvi.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "org.iesvi.ws.Book", targetNamespace = "http://ws.iesvi.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Book {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "getBookByAuthor", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.GetBookByAuthor")
    @ResponseWrapper(localName = "getBookByAuthorResponse", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.GetBookByAuthorResponse")
    @Action(input = "http://ws.iesvi.org/Book/getBookByAuthorRequest", output = "http://ws.iesvi.org/Book/getBookByAuthorResponse")
    public void getBookByAuthor(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "getBookByEditorial", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.GetBookByEditorial")
    @ResponseWrapper(localName = "getBookByEditorialResponse", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.GetBookByEditorialResponse")
    @Action(input = "http://ws.iesvi.org/Book/getBookByEditorialRequest", output = "http://ws.iesvi.org/Book/getBookByEditorialResponse")
    public void getBookByEditorial(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "getBookByTitle", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.GetBookByTitle")
    @ResponseWrapper(localName = "getBookByTitleResponse", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.GetBookByTitleResponse")
    @Action(input = "http://ws.iesvi.org/Book/getBookByTitleRequest", output = "http://ws.iesvi.org/Book/getBookByTitleResponse")
    public void getBookByTitle(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteBook", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.DeleteBook")
    @ResponseWrapper(localName = "deleteBookResponse", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.DeleteBookResponse")
    @Action(input = "http://ws.iesvi.org/Book/deleteBookRequest", output = "http://ws.iesvi.org/Book/deleteBookResponse")
    public void deleteBook(
        @WebParam(name = "arg0", targetNamespace = "")
        BookImpl arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateBook", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.UpdateBook")
    @ResponseWrapper(localName = "updateBookResponse", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.UpdateBookResponse")
    @Action(input = "http://ws.iesvi.org/Book/updateBookRequest", output = "http://ws.iesvi.org/Book/updateBookResponse")
    public void updateBook(
        @WebParam(name = "arg0", targetNamespace = "")
        BookImpl arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "getBookList", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.GetBookList")
    @ResponseWrapper(localName = "getBookListResponse", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.GetBookListResponse")
    @Action(input = "http://ws.iesvi.org/Book/getBookListRequest", output = "http://ws.iesvi.org/Book/getBookListResponse")
    public void getBookList();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addBook", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.AddBook")
    @ResponseWrapper(localName = "addBookResponse", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.AddBookResponse")
    @Action(input = "http://ws.iesvi.org/Book/addBookRequest", output = "http://ws.iesvi.org/Book/addBookResponse")
    public void addBook(
        @WebParam(name = "arg0", targetNamespace = "")
        BookImpl arg0);

}
