
package org.iesvi.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Book", targetNamespace = "http://ws.iesvi.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Book {


    /**
     * 
     * @return
     *     returns java.util.List<org.iesvi.ws.BookModel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookList", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.GetBookList")
    @ResponseWrapper(localName = "getBookListResponse", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.GetBookListResponse")
    @Action(input = "http://ws.iesvi.org/Book/getBookListRequest", output = "http://ws.iesvi.org/Book/getBookListResponse")
    public List<BookModel> getBookList();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addBook", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.AddBook")
    @ResponseWrapper(localName = "addBookResponse", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.AddBookResponse")
    @Action(input = "http://ws.iesvi.org/Book/addBookRequest", output = "http://ws.iesvi.org/Book/addBookResponse")
    public void addBook(
        @WebParam(name = "arg0", targetNamespace = "")
        BookModel arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteBookById", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.DeleteBookById")
    @ResponseWrapper(localName = "deleteBookByIdResponse", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.DeleteBookByIdResponse")
    @Action(input = "http://ws.iesvi.org/Book/deleteBookByIdRequest", output = "http://ws.iesvi.org/Book/deleteBookByIdResponse")
    public void deleteBookById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteBookByPosition", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.DeleteBookByPosition")
    @ResponseWrapper(localName = "deleteBookByPositionResponse", targetNamespace = "http://ws.iesvi.org/", className = "org.iesvi.ws.DeleteBookByPositionResponse")
    @Action(input = "http://ws.iesvi.org/Book/deleteBookByPositionRequest", output = "http://ws.iesvi.org/Book/deleteBookByPositionResponse")
    public void deleteBookByPosition(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
